server {
    listen 80;
    server_name 52.15.126.66;

    # Static 파일 직접 서빙
    location /static/ {
        alias /app/staticfiles/;
    }

    # Media 파일 직접 서빙
    location /media/ {
        alias /app/media/;
    }

    # FastAPI 프록시
    location /ai/ {
        proxy_pass http://fastapi:8001/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Django 프록시
    location / {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
