# Generated by Django 6.0.3 on 2026-04-06 01:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
        ('reviews', '0002_alter_review_options_alter_reviewai_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewbookmark',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='reviewcomment',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='reviewlike',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='reviewreport',
            options={'ordering': ['-id']},
        ),
        migrations.AlterUniqueTogether(
            name='reviewbookmark',
            unique_together={('user', 'review')},
        ),
        migrations.AlterUniqueTogether(
            name='reviewreport',
            unique_together={('user', 'review')},
        ),
    ]
