apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: product-review
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "django-insecure-_k4%ob23#p=ax+#phphf^zik)@s5)ru=rm1atq43u5jp0m)1ec"
  DB_PASSWORD: "password"
